//create an account
POST  http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "PurpleNGreen",
    "userhandle": "GrapeMan",
    "password": "MyPassword",
    "profilePic": "default"
}

###
//log in
POST  http://localhost:3000/api/users/login
Content-Type: application/json

{
    "userhandle": "GrapeMan",
    "password": "MyPassword"
}


###
//get All Users
GET http://localhost:3000/api/users

###
//get all tweets
GET http://localhost:3000/api/tweets


###
//post a tweet
POST http://localhost:3000/api/tweets
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJQdXJwbGVOR3JlZW4iLCJ1c2VyaGFuZGxlIjoiQEdyYXBlTWFuIiwiUEZQbmFtZSI6ImRlZmF1bHQiLCJpYXQiOjE2Mzg0OTQ1MDF9.BJykHeAHF9CbI6Yckp_z6-Hs7gqFpwniK67DziZaIWM

{
    "authorHandle": "GrapeMan",
    "tweetContent": "Tweet 1"
}

###
//get tweet by id
GET http://localhost:3000/api/tweets/7/id


###
//delete tweet by id
DELETE http://localhost:3000/api/tweets/7
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJQdXJwbGVOR3JlZW4iLCJ1c2VyaGFuZGxlIjoiQEdyYXBlTWFuIiwiUEZQbmFtZSI6ImRlZmF1bHQiLCJpYXQiOjE2Mzg0OTQ1MDF9.BJykHeAHF9CbI6Yckp_z6-Hs7gqFpwniK67DziZaIWM

{
    "userhandle": "GrapeMan"
}

###
//Get all comments by tweet ID
GET http://localhost:3000/api/comments/7/id

###
//Create a comment on a tweet
POST http://localhost:3000/api/comments/7
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJQdXJwbGVOR3JlZW4iLCJ1c2VyaGFuZGxlIjoiQEdyYXBlTWFuIiwiUEZQbmFtZSI6ImRlZmF1bHQiLCJpYXQiOjE2Mzg0OTQ1MDF9.BJykHeAHF9CbI6Yckp_z6-Hs7gqFpwniK67DziZaIWM

{
    "authorHandle": "GrapeMan",
    "commentContent": "Comment 1"
}

###
//Delete a comment by comment ID
DELETE http://localhost:3000/api/comments/7
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJQdXJwbGVOR3JlZW4iLCJ1c2VyaGFuZGxlIjoiQEdyYXBlTWFuIiwiUEZQbmFtZSI6ImRlZmF1bHQiLCJpYXQiOjE2Mzg0OTQ1MDF9.BJykHeAHF9CbI6Yckp_z6-Hs7gqFpwniK67DziZaIWM

{
    "userhandle": "GrapeMan"
}

###
//Delete a users account
DELETE http://localhost:3000/api/users/GrapeMan
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidXNlcm5hbWUiOiJQdXJwbGVOR3JlZW4iLCJ1c2VyaGFuZGxlIjoiQEdyYXBlTWFuIiwiUEZQbmFtZSI6ImRlZmF1bHQiLCJpYXQiOjE2Mzg0OTQ1MDF9.BJykHeAHF9CbI6Yckp_z6-Hs7gqFpwniK67DziZaIWM

{
    "userhandleReq": "GrapeMan"
}